#!/bin/sh
prg=`basename $0`

live_tmp="$SHARED_INSTALLER_TEMP/live_conf.txt"
sample_tmp="$SHARED_INSTALLER_TEMP/sample_conf.txt"

# Retreive the information preinstall stored for us. We can't look this up
# ourselves.
live_config=`cat "$live_tmp"`
sample_config=`cat "$sample_tmp"`

if [ -e "$live_config" ]; then
	echo "cgit: $live_config exists, leaving it alone."
	exit 0
fi

if [ ! -r "$sample_config" ]; then
	echo "cgit: $sample_config not packaged. Can't create initial config."
	exit 0
fi

echo "cgit: $live_config does NOT exist. Creating it."
cp "$sample_config" "$live_config"

exit 0
